OnlineQuiz/OnlineQuiz/Controllers/StudentHomeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.SessionState;
using OnlineQuiz.Models;

namespace OnlineQuiz.Controllers
{
    public class StudentHomeController : Controller
    {
        public ActionResult Index()
        {
            QuizContext db = new QuizContext();
            int user_id = (int) Session["UserID"];

            var user_record = db.UserQuizRecords.Where(x => x.UserID == user_id);
            return View(user_record);
        }

        public ActionResult ViewAllSubjects()
        {
            QuizContext db = new QuizContext();
            return View(db.Subjects.ToList());
        }

        public ActionResult ViewAllQuestions(int? id)
        {
            QuizContext db = new QuizContext();
            //var questions = db.Questions.Where(q => q.SubjectID==id);

            var questions = (from q in db.Questions
                orderby Guid.NewGuid()
                where q.SubjectID==id
                select q).Take(5);

            var sname = db.Subjects.Where(q => q.SubjectID == id).SingleOrDefault();
            Session["SubjectName"] = sname.SubjectName;
            return View(questions);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Result(string option1, string option2, string option3, string option4, string option5)
        {
            int correct_answers = 0;
            int count = 0, temp=0;

            //Following list contains questionID for retrieving questions from DB
            List<int> questionsids = new List<int>()
            {
                (int)Session["QID1"],
                (int)Session["QID2"],
                (int)Session["QID3"],
                (int)Session["QID4"],
                (int)Session["QID5"]
            };

            //Following list contains list of options user have selected
            List<String> option_list = new List<string>()
            {
                option1, option2, option3, option4, option5
            };

            QuizContext context = new QuizContext();

            foreach (var item in option_list)
            {
                temp = questionsids[count];
                var result = context.Questions.Where(x => x.CorrectOption == item && x.QuestionID == temp).FirstOrDefault();
                count += 1;

                if (result != null)
                {
                    correct_answers += 1;
                }
            }

            UserQuizRecord userrecord = new UserQuizRecord();
            userrecord.UserID = (int) Session["UserID"];
            userrecord.Username = (string) Session["Username"];
            userrecord.SubjectName = (string) Session["SubjectName"];
            userrecord.QuizDate = DateTime.Now;
            userrecord.MarksObtained = correct_answers;

            context.UserQuizRecords.Add(userrecord);
            context.SaveChanges();
            ViewBag.correctAnswers = correct_answers;
            return View();
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index", "Student");
        }
    }
}

OnlineQuiz/OnlineQuiz/Views/StudentHome/Index.cshtml
@model IEnumerable<OnlineQuiz.Models.UserQuizRecord>

@{
    ViewBag.Title = "Index";
}

@Html.Partial("_Logout")


<p style="float: right; font-size: 17px;">Username : <b style="color: cornflowerblue">@Session["Username"]</b></p>
<br/>
<p>@Html.ActionLink("Logout", "Logout")</p>
<br />

<h1 align="center">Student Panel</h1><hr/>

@Html.ActionLink("Give another quiz", "ViewAllSubjects")<br/>

<br/>
<h3>Your Quizzes Result</h3>
<table class="table">
<tr>
    <th>
        @Html.DisplayNameFor(model => model.SubjectName)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.QuizDate)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.MarksObtained)
    </th>
    <th></th>
</tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SubjectName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.QuizDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MarksObtained)
        </td>
    </tr>
}
</table>

OnlineQuiz/OnlineQuiz/Views/StudentHome/Result.cshtml
@model OnlineQuiz.Models.UserQuizRecord


@{
    ViewBag.Title = "Result";
}

<h2>Result</h2>

<p>Total Questions : 5</p>
<p>Correct Answers : @ViewBag.correctAnswers</p>
<p>Total Marks : 5</p>
<br />
@Html.ActionLink("Go to Subject Menu", "ViewAllSubjects")


OnlineQuiz/OnlineQuiz/Views/StudentHome/ViewAllQuestions.cshtml
@model IEnumerable<OnlineQuiz.Models.Question>

@{
    ViewBag.Title = "ViewAllQuestions";
}

<script type="text/javascript">
    function submitResult() {
        confirm("Are you sure you want to submit the result?");
    }

</script>

<h1 align="center">Quiz</h1>

@{
    var li = new List<string> {"1", "2", "3", "4", "5"};
    int count = 0;
}

@using (Html.BeginForm("Result", "StudentHome"))
{
    <ol>
        @foreach (var item in Model)
        {
            Session["QID"+li[count]] = item.QuestionID;
            <li>
                @Html.HiddenFor(modelItem => item.QuestionID)
                @Html.DisplayFor(modelItem => item.Question1)
                <br/>
                <br/>
                @Html.RadioButton("option" + li[count], item.Option1) @item.Option1
                <br/>
                @Html.RadioButton("option" + li[count++], item.Option2) @item.Option2
                <br/>
            </li>
            <hr/>
        }
    </ol>
    <p align="center"><input type="submit" name="submit" value="Submit Quiz" class="btn btn-success" style="width:20%;"/></p>
}

OnlineQuiz/OnlineQuiz/Views/StudentHome/ViewAllSubjects.cshtml
@model IEnumerable<OnlineQuiz.Models.Subject>

@{
    ViewBag.Title = "ViewAllSubjects";
}

@Html.ActionLink("Go to Main Page", "Index")

<div class="container">
    <br/>
    <h4>Select Subject for Quiz</h4>
    <hr/>
    @foreach (var item in Model)
    {
        <p>@Html.ActionLink(item.SubjectName, "ViewAllQuestions", new {id = item.SubjectID})</p>
    }

</div>