OnlineQuiz/OnlineQuiz/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineQuiz.Models;

namespace OnlineQuiz.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin

        public ActionResult MainPage()
        {
            return View();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewUsersRecord(string searchTerm)
        {
            QuizContext db = new QuizContext();
            var result = db.UserQuizRecords;

            if (!String.IsNullOrEmpty(searchTerm))
            {
                var fresult = result.Where(x => x.Username.Contains(searchTerm));
                return View(fresult);
            }
            return View(result);
        }

        public ActionResult GetStudents(string term)
        {
            QuizContext db = new QuizContext();
            var result = db.UserQuizRecords;
            List<string> students = result.Where(s => s.Username.Contains(term))
                .Take(5)
                .Select(x => x.Username).ToList();

            return Json(students, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(int? id)
        {
            QuizContext db = new QuizContext();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            UserQuizRecord record = db.UserQuizRecords.Find(id);
            if (record == null)
            {
                return HttpNotFound();
            }
            return View(record);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            QuizContext db = new QuizContext();
            UserQuizRecord record = db.UserQuizRecords.Find(id);
            db.UserQuizRecords.Remove(record);
            db.SaveChanges();

            return RedirectToAction("ViewUsersRecord");
        }

    }
}

OnlineQuiz/OnlineQuiz/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineQuiz.Models;

namespace OnlineQuiz.Controllers
{
    public class QuestionsController : Controller
    {
        private QuizContext db = new QuizContext();

        // GET: Questions
        public ActionResult Index(string searchString)
        {
            var questions = db.Questions.Include(q => q.Subject);

            if (!String.IsNullOrEmpty(searchString))
            {
                questions = db.Questions.Where(q => q.Subject.SubjectName.Contains(searchString));
            }
            return View(questions.ToList());
        }

        // GET: Questions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // GET: Questions/Create
        public ActionResult Create()
        {
            ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "SubjectName");
            return View();
        }

        // POST: Questions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "SubjectID,QuestionID,Question1,Option1,Option2,CorrectOption")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "SubjectName", question.SubjectID);
            return View(question);
        }

        // GET: Questions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "SubjectName", question.SubjectID);
            return View(question);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "SubjectID,QuestionID,Question1,Option1,Option2,CorrectOption")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "SubjectName", question.SubjectID);
            return View(question);
        }

        // GET: Questions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineQuiz/OnlineQuiz/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineQuiz.Models;

namespace OnlineQuiz.Controllers
{
    public class StudentController : Controller
    {
        // GET: Student
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Authorize(Login login)
        {
            QuizContext quizContext = new QuizContext();

            var userDetails = quizContext.Logins
                .Where(x => x.Username == login.Username && x.Password == login.Password).FirstOrDefault();

            if (userDetails == null)
            {
                login.loginErrorMessage = "Wrong username or password";
                return View("Index", login);
            }
            else
            {
                Session["UserID"] = userDetails.UserID;
                Session["Username"] = login.Username;
                return RedirectToAction("Index", "StudentHome");
            }
        }
    }
}

OnlineQuiz/OnlineQuiz/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineQuiz.Models;

namespace OnlineQuiz.Controllers
{
    public class SubjectsController : Controller
    {
        private QuizContext db = new QuizContext();

        // GET: Subjects
        public ActionResult Index()
        {
            return View(db.Subjects.ToList());
        }

        // GET: Subjects/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Subjects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SubjectID,SubjectName")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                db.Subjects.Add(subject);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(subject);
        }

        // GET: Subjects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = db.Subjects.Find(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(subject);
        }

        // POST: Subjects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SubjectID,SubjectName")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                db.Entry(subject).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(subject);
        }

        // GET: Subjects/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = db.Subjects.Find(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(subject);
        }

        // POST: Subjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Subject subject = db.Subjects.Find(id);
            //Below statement first removes all questions from question table
            //Reason: it uses foreign key and if we try to delete subject before deleting all its related questions error occurs
            db.Questions.RemoveRange(db.Questions.Where(x => x.SubjectID == id));
            db.Subjects.Remove(subject);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineQuiz/OnlineQuiz/Views/Admin/Delete.cshtml
@model OnlineQuiz.Models.UserQuizRecord

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserQuizRecord</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuizDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuizDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MarksObtained)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MarksObtained)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Login.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Login.Username)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ViewUsersRecord")
        </div>
    }
</div>

OnlineQuiz/OnlineQuiz/Views/Admin/Index.cshtml


@{
    ViewBag.Title = "Admin Panel";
}

<h2>Admin Panel</h2>
<br/>
<div class="container">
   
    <p>@Html.ActionLink("Add/Remove Subjects", "Index", "Subjects")</p>
    <p>@Html.ActionLink("Add/Remove Questions", "Index", "Questions")</p>
    <p>@Html.ActionLink("View User Records", "ViewUsersRecord")</p>

</div>


OnlineQuiz/OnlineQuiz/Views/Admin/MainPage.cshtml

@{
    ViewBag.Title = "MainPage";
}

<h2 align="center">Welcome To Online Quiz Application</h2>

<style>
    .btn-xl {
        padding: 10px 20px;
        font-size: 20px;
        border-radius: 10px;
    }
</style>
<br/><br /><br /><br />

<p align="center">
    @Html.ActionLink("Login as Student", "Index", "Student", null, new { @class = "btn btn-primary btn-xl" })
    @Html.ActionLink("Login as Admin", "Index", "Admin", null, new { @class = "btn btn-primary btn-xl" })
</p>

OnlineQuiz/OnlineQuiz/Views/Admin/ViewUsersRecord.cshtml
@model IEnumerable<OnlineQuiz.Models.UserQuizRecord>

<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/cupertino/jquery-ui.css" type="text/css" rel="Stylesheet" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js" type="text/javascript"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js" type="text/javascript"></script>

<script type="text/javascript">
    $(function () {
        $("#txtSearch").autocomplete({
            source: '@Url.Action("GetStudents")',
            minLength: 1,
            select : submitAutocompleteForm
        });
    });


    var submitAutocompleteForm = function(event, ui) {
        var $input = $(this);
        $input.val(ui.item.label);

        var $form = $input.parents("form:first");
        $form.submit();
    };

</script>

@Html.ActionLink("Go to Admin Panel", "Index")
<h2>Students Quiz Result</h2><br />

@using(@Html.BeginForm())
{
    <b>Name: </b>
    @Html.TextBox("searchTerm", null, new { id = "txtSearch" })
    <input type="submit" value="Search" />
}﻿

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubjectName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QuizDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MarksObtained)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>@Html.DisplayFor(modeiItem => item.UserID)</td>
        <td>
            @Html.DisplayFor(modelItem => item.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SubjectName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.QuizDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MarksObtained)
        </td>
        <td>
            @Html.ActionLink("Delete", "Delete", new {id = item.QuizID})
        </td>
    </tr>
}

</table>

